# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc8ebc9b3f72dd190eeb54229c775c9fee60dccc1fa065c363b4f95575113919b5f301938c0350ed19dbcd5c9893bd57e59d578b43f553d412a34e5b909e6265

test:
  secret_key_base: eff310c2b92ee0e814c825d42d46a0fb6f0aa3fd7372d40360dda50b2027cdfc567c98b38ec38648d8869201af573a28fa9e10c2fa154d89894d654fac37bd80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
